# Create a simple playbook that prints "Hello, World!" to the console.
- name: A playbook to print Hello World
  hosts: localhost

  tasks:
  - name: Print Hello World 
    debug:
      msg: "Hello, World!"

# command: ansible-playbook problem_1.yml
